language: node_js
node_js:
  - lts/*
env:
  - WEB_INDEX=docs/.vuepress/dist/index.html
install:
  - yarn
  - yarn upgrade
script:
  - yarn build
  - test -f $WEB_INDEX -a -s $WEB_INDEX
deploy:
  email: taichunmin@gmail.com
  github-token: $GITHUB_TOKEN # a token generated on github allowing travis to push code on you repository
  keep-history: true
  local_dir: docs/.vuepress/dist
  name: taichunmin
  provider: pages
  skip-cleanup: true
  target-branch: master
  on:
    branch: vuepress
branches:
  only:
    - vuepress
notifications:
  email:
    on_failure: always
