theme: jekyll-theme-cayman
timezone: Asia/Taipei
title: 筆記國度
description: 在這裡放著一些我自己的筆記
show_downloads: false
google_analytics: UA-96342273-1
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      author: 戴均民
