# Setup
title:        筆記國度
url:          http://blog.taichunmin.tk/
tagline:      在這裡放著一些我自己的筆記
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       戴均民
  url:        http://taichunmin.idv.tw/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
